const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

async function generateGridFromV2Generator() {
    console.log('Démarrage de la génération avec le générateur v2...');
    
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    try {
        const page = await browser.newPage();
        
        // Lire le fichier JSON
        const jsonPath = path.join(__dirname, 'json_files/v3/AVP_v3.json');
        const jsonContent = fs.readFileSync(jsonPath, 'utf8');
        
        // Ouvrir le générateur v2
        const generatorPath = 'file://' + path.join(__dirname, 'Chablon/Generateur_de_Grilles_ECOS_v2.html');
        await page.goto(generatorPath);
        
        // Attendre que la page soit chargée
        await page.waitForSelector('#jsonInput');
        
        // Coller le JSON dans le textarea
        await page.evaluate((json) => {
            document.getElementById('jsonInput').value = json;
        }, jsonContent);
        
        // Cliquer sur le bouton de génération
        await page.click('#generateBtn');
        
        // Attendre que la prévisualisation soit visible
        await page.waitForSelector('#previewSection', { visible: true, timeout: 10000 });
        
        // Attendre un peu plus pour s'assurer que le HTML est généré
        await new Promise(resolve => setTimeout(resolve, 1000));
        
        // Vérifier s'il y a des erreurs
        const errorMessage = await page.evaluate(() => {
            const errorDiv = document.getElementById('errorMessage');
            return errorDiv ? errorDiv.textContent : '';
        });
        
        if (errorMessage) {
            throw new Error(`Erreur de génération: ${errorMessage}`);
        }
        
        // Déboguer et récupérer le HTML généré
        const debugInfo = await page.evaluate(() => {
            return {
                hasGeneratedHTML: typeof window.generatedHTML !== 'undefined',
                generatedHTMLLength: window.generatedHTML ? window.generatedHTML.length : 0,
                previewVisible: document.getElementById('previewSection')?.style.display,
                iframeSrc: document.getElementById('previewFrame')?.srcdoc?.substring(0, 100)
            };
        });
        
        console.log('Debug info:', debugInfo);
        
        // Récupérer le HTML généré depuis la variable globale
        let generatedHTML = await page.evaluate(() => {
            return window.generatedHTML || '';
        });
        
        if (!generatedHTML) {
            // Essayer de récupérer depuis l'iframe
            generatedHTML = await page.evaluate(() => {
                const iframe = document.getElementById('previewFrame');
                return iframe ? iframe.srcdoc : '';
            });
            
            if (generatedHTML) {
                console.log('HTML récupéré depuis l\'iframe');
            } else {
                throw new Error('Aucun HTML généré trouvé');
            }
        }
        
        // Sauvegarder le fichier HTML
        const outputDir = path.join(__dirname, 'grilles_generees/html/v3');
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }
        
        const outputPath = path.join(outputDir, 'AVP_v3 - Grille ECOS-test.html');
        fs.writeFileSync(outputPath, generatedHTML, 'utf8');
        
        console.log(`Grille générée avec succès : ${outputPath}`);
        
        // Comparer avec le fichier généré automatiquement
        const autoGeneratedPath = path.join(outputDir, 'AVP_v3 - Grille ECOS.html');
        if (fs.existsSync(autoGeneratedPath)) {
            const autoGeneratedContent = fs.readFileSync(autoGeneratedPath, 'utf8');
            
            if (generatedHTML === autoGeneratedContent) {
                console.log('\n✅ Les deux fichiers sont identiques !');
            } else {
                console.log('\n⚠️  Des différences ont été détectées entre les deux fichiers.');
                
                // Analyser les différences principales
                const manualLines = generatedHTML.split('\n');
                const autoLines = autoGeneratedContent.split('\n');
                
                console.log(`\nNombre de lignes - Manuel: ${manualLines.length}, Auto: ${autoLines.length}`);
                
                // Trouver les premières lignes différentes
                for (let i = 0; i < Math.min(manualLines.length, autoLines.length); i++) {
                    if (manualLines[i] !== autoLines[i]) {
                        console.log(`\nPremière différence à la ligne ${i + 1}:`);
                        console.log('Manuel:', manualLines[i].substring(0, 100) + '...');
                        console.log('Auto:  ', autoLines[i].substring(0, 100) + '...');
                        break;
                    }
                }
            }
        } else {
            console.log('\n⚠️  Le fichier auto-généré n\'existe pas pour la comparaison.');
        }
        
    } catch (error) {
        console.error('Erreur lors de la génération:', error);
    } finally {
        await browser.close();
    }
}

generateGridFromV2Generator();